"""
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \\dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
"""

def sum_even_fibonacci_numbers():
    n1 = 0
    n2 = 1
    even_sum = 0
    
    while True:
        n = n1 + n2

        if n % 2 == 0:
            even_sum += n

        n1 = n2
        n2 = n

        if n >= 4e6:
            return even_sum
        

def main():
    print(sum_even_fibonacci_numbers()) # 4613732

if __name__ == '__main__':
    main()